apiVersion: v1
kind: Service
metadata:
  name: protego-api
  namespace: default
  labels:
    app: protego-api
    service: api
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: protego-api
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800

