apiVersion: v1
kind: ConfigMap
metadata:
  name: protego-config
  namespace: default
data:
  SCRAPER_SCHEDULE_CRON: "0 2 * * *"
  SCRAPER_ENABLED: "true"
  SCRAPER_TIMEOUT_SECONDS: "300"
  SCRAPER_RETRY_ATTEMPTS: "3"
  SCRAPER_RETRY_DELAY_SECONDS: "60"
  ANALYSIS_ENABLED: "true"
  ANALYSIS_POLL_INTERVAL_SECONDS: "300"
  ANALYSIS_BATCH_SIZE: "100"
  API_HOST: "0.0.0.0"
  API_PORT: "8000"
  API_RELOAD: "false"
  API_WORKERS: "4"
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "json"
  LOG_ROTATION_DAYS: "30"
  LOG_MAX_BYTES: "10485760"
  LOG_BACKUP_COUNT: "5"
  HTTP_TIMEOUT_SECONDS: "30"
  HTTP_MAX_RETRIES: "3"
  HTTP_RETRY_DELAY_SECONDS: "5"
  DAILYMED_BASE_URL: "https://dailymed.nlm.nih.gov"
  CLINICAL_TRIALS_API_BASE_URL: "https://clinicaltrials.gov/api/v2"
  CLINICAL_TRIALS_API_TIMEOUT_SECONDS: "60"
  ENVIRONMENT: "production"
  APP_NAME: "protego-health-backend"
  APP_VERSION: "1.0.0"

